#pragma once
extern long ierr;
extern char herr[255];

// Definitions of the Refprop types
typedef void(__stdcall *fp_ABFL1dllTYPE)(double &, double &, double *, long &, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_ABFL2dllTYPE)(double &, double &, double *, long &, long &, double &, double &, double &, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double *, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_ACTVYdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_AGdllTYPE)(double &, double &, double *, double &, double &);
typedef void(__stdcall *fp_CCRITdllTYPE)(double &, double &, double &, double *, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_CP0dllTYPE)(double &, double *, double &);
typedef void(__stdcall *fp_CRITPdllTYPE)(double *, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_CSATKdllTYPE)(long &, double &, long &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_CV2PKdllTYPE)(long &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_CVCPKdllTYPE)(long &, double &, double &, double &, double &);
typedef void(__stdcall *fp_CVCPdllTYPE)(double &, double &, double *, double &, double &);
typedef void(__stdcall *fp_DBDTdllTYPE)(double &, double *, double &);
typedef void(__stdcall *fp_DBFL1dllTYPE)(double &, double &, double *, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_DBFL2dllTYPE)(double &, double &, double *, long &, double &, double &, double &, double &, double &, double *, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_DDDPdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_DDDTdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_DEFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_DHD1dllTYPE)(double &, double &, double *, double &, double &, double &, double &, double &, double &);
typedef void(__stdcall *fp_DHFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_DIELECdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_DOTFILLdllTYPE)(long &, double *, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_DPDD2dllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_DPDDKdllTYPE)(long &, double &, double &, double &);
typedef void(__stdcall *fp_DPDDdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_DPDTKdllTYPE)(long &, double &, double &, double &);
typedef void(__stdcall *fp_DPDTdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_DPTSATKdllTYPE)(long &, double &, long &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_DSFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_ENTHALdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_ENTROdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_ESFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_FGCTYdllTYPE)(double &, double &, double *, double *);
typedef void(__stdcall *fp_FPVdllTYPE)(double &, double &, double &, double *, double &);
typedef void(__stdcall *fp_GERG04dllTYPE)(long &, long &, long &, char*, long);
typedef void(__stdcall *fp_GETFIJdllTYPE)(char*, double *, char*, char*, long, long, long);
typedef void(__stdcall *fp_GETKTVdllTYPE)(long &, long &, char*, double *, char*, char*, char*, char*, long, long, long, long, long);
typedef void(__stdcall *fp_GIBBSdllTYPE)(double &, double &, double *, double &, double &);
typedef void(__stdcall *fp_HSFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_INFOdllTYPE)(long &, double &, double &, double &, double &, double &, double &, double &, double &, double &, double &);
typedef void(__stdcall *fp_LIMITKdllTYPE)(char*, long &, double &, double &, double &, double &, double &, double &, double &, long &, char*, long, long);
typedef void(__stdcall *fp_LIMITSdllTYPE)(char*, double *, double &, double &, double &, double &, long);
typedef void(__stdcall *fp_LIMITXdllTYPE)(char*, double &, double &, double &, double *, double &, double &, double &, double &, long &, char*, long, long);
typedef void(__stdcall *fp_MELTPdllTYPE)(double &, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_MELTTdllTYPE)(double &, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_MLTH2OdllTYPE)(double &, double &, double &);
typedef void(__stdcall *fp_NAMEdllTYPE)(long &, char*, char*, char*, long, long, long);
typedef void(__stdcall *fp_PDFL1dllTYPE)(double &, double &, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_PDFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_PEFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_PHFL1dllTYPE)(double &, double &, double *, long &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_PHFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_PQFLSHdllTYPE)(double &, double &, double *, long &, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_PREOSdllTYPE)(long &);
typedef void(__stdcall *fp_PRESSdllTYPE)(double &, double &, double *, double &);
typedef void(__stdcall *fp_PSFL1dllTYPE)(double &, double &, double *, long &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_PSFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_PUREFLDdllTYPE)(long &);
typedef void(__stdcall *fp_QMASSdllTYPE)(double &, double *, double *, double &, double *, double *, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_QMOLEdllTYPE)(double &, double *, double *, double &, double *, double *, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_SATDdllTYPE)(double &, double *, long &, long &, double &, double &, double &, double &, double *, double *, long &, char*, long);
typedef void(__stdcall *fp_SATEdllTYPE)(double &, double *, long &, long &, long &, double &, double &, double &, long &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_SATHdllTYPE)(double &, double *, long &, long &, long &, double &, double &, double &, long &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_SATPdllTYPE)(double &, double *, long &, double &, double &, double &, double *, double *, long &, char*, long);
typedef void(__stdcall *fp_SATSdllTYPE)(double &, double *, long &, long &, long &, double &, double &, double &, long &, double &, double &, double &, long &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_SATTdllTYPE)(double &, double *, long &, double &, double &, double &, double *, double *, long &, char*, long);
typedef void(__stdcall *fp_SETAGAdllTYPE)(long &, char*, long);
typedef void(__stdcall *fp_SETKTVdllTYPE)(long &, long &, char*, double *, char*, long &, char*, long, long, long);
typedef void(__stdcall *fp_SETMIXdllTYPE)(char*, char*, char*, long &, char*, double *, long &, char*, long, long, long, long, long);
typedef void(__stdcall *fp_SETMODdllTYPE)(long &, char*, char*, char*, long &, char*, long, long, long, long);
typedef void(__stdcall *fp_SETREFdllTYPE)(char*, long &, double *, double &, double &, double &, double &, long &, char*, long, long);
typedef void(__stdcall *fp_SETUPdllTYPE)(long &, char*, char*, char*, long &, char*, long, long, long, long);
typedef void(__stdcall *fp_SPECGRdllTYPE)(double &, double &, double &, double &);
typedef void(__stdcall *fp_SUBLPdllTYPE)(double &, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_SUBLTdllTYPE)(double &, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_SURFTdllTYPE)(double &, double &, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_SURTENdllTYPE)(double &, double &, double &, double *, double *, double &, long &, char*, long);
typedef void(__stdcall *fp_TDFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_TEFLSHdllTYPE)(double &, double &, double *, long &, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_THERM0dllTYPE)(double &, double &, double *, double &, double &, double &, double &, double &, double &, double &, double &, double &);
typedef void(__stdcall *fp_THERM2dllTYPE)(double &, double &, double *, double &, double &, double &, double &, double &, double &, double &, double *, double &, double &, double &, double &, double &, double &, double &, double &, double &, double &, double &, double &, double &, double &);
typedef void(__stdcall *fp_THERM3dllTYPE)(double &, double &, double *, double &, double &, double &, double &, double &, double &, double &, double &, double &, double &);
typedef void(__stdcall *fp_THERMdllTYPE)(double &, double &, double *, double &, double &, double &, double &, double &, double &, double &, double &);
typedef void(__stdcall *fp_THFLSHdllTYPE)(double &, double &, double *, long &, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_TPFLSHdllTYPE)(double &, double &, double *, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_TPRHOdllTYPE)(double &, double &, double *, long &, long &, double &, long &, char*, long);
typedef void(__stdcall *fp_TQFLSHdllTYPE)(double &, double &, double *, long &, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_TRNPRPdllTYPE)(double &, double &, double *, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_TSFLSHdllTYPE)(double &, double &, double *, long &, double &, double &, double &, double &, double *, double *, double &, double &, double &, double &, double &, double &, long &, char*, long);
typedef void(__stdcall *fp_VIRBdllTYPE)(double &, double *, double &);
typedef void(__stdcall *fp_VIRCdllTYPE)(double &, double *, double &);
typedef void(__stdcall *fp_WMOLdllTYPE)(double *, double &);
typedef void(__stdcall *fp_XMASSdllTYPE)(double *, double *, double &);
typedef void(__stdcall *fp_XMOLEdllTYPE)(double *, double *, double &);
typedef void(__stdcall *fp_HEATdllTYPE)(double &, double &, double *, double &, double &, long &, char*, long);



//Define explicit function pointers
extern fp_ABFL1dllTYPE ABFL1dll;
extern fp_ABFL2dllTYPE ABFL2dll;
extern fp_ACTVYdllTYPE ACTVYdll;
extern fp_AGdllTYPE AGdll;
extern fp_CCRITdllTYPE CCRITdll;
extern fp_CP0dllTYPE CP0dll;
extern fp_CRITPdllTYPE CRITPdll;
extern fp_CSATKdllTYPE CSATKdll;
extern fp_CV2PKdllTYPE CV2PKdll;
extern fp_CVCPKdllTYPE CVCPKdll;
extern fp_CVCPdllTYPE CVCPdll;
extern fp_DBDTdllTYPE DBDTdll;
extern fp_DBFL1dllTYPE DBFL1dll;
extern fp_DBFL2dllTYPE DBFL2dll;
extern fp_DDDPdllTYPE DDDPdll;
extern fp_DDDTdllTYPE DDDTdll;
extern fp_DEFLSHdllTYPE DEFLSHdll;
extern fp_DHD1dllTYPE DHD1dll;
extern fp_DHFLSHdllTYPE DHFLSHdll;
extern fp_DIELECdllTYPE DIELECdll;
extern fp_DOTFILLdllTYPE DOTFILLdll;
extern fp_DPDD2dllTYPE DPDD2dll;
extern fp_DPDDKdllTYPE DPDDKdll;
extern fp_DPDDdllTYPE DPDDdll;
extern fp_DPDTKdllTYPE DPDTKdll;
extern fp_DPDTdllTYPE DPDTdll;
extern fp_DPTSATKdllTYPE DPTSATKdll;
extern fp_DSFLSHdllTYPE DSFLSHdll;
extern fp_ENTHALdllTYPE ENTHALdll;
extern fp_ENTROdllTYPE ENTROdll;
extern fp_ESFLSHdllTYPE ESFLSHdll;
extern fp_FGCTYdllTYPE FGCTYdll;
extern fp_FPVdllTYPE FPVdll;
extern fp_GERG04dllTYPE GERG04dll;
extern fp_GETFIJdllTYPE GETFIJdll;
extern fp_GETKTVdllTYPE GETKTVdll;
extern fp_GIBBSdllTYPE GIBBSdll;
extern fp_HSFLSHdllTYPE HSFLSHdll;
extern fp_INFOdllTYPE INFOdll;
extern fp_LIMITKdllTYPE LIMITKdll;
extern fp_LIMITSdllTYPE LIMITSdll;
extern fp_LIMITXdllTYPE LIMITXdll;
extern fp_MELTPdllTYPE MELTPdll;
extern fp_MELTTdllTYPE MELTTdll;
extern fp_MLTH2OdllTYPE MLTH2Odll;
extern fp_NAMEdllTYPE NAMEdll;
extern fp_PDFL1dllTYPE PDFL1dll;
extern fp_PDFLSHdllTYPE PDFLSHdll;
extern fp_PEFLSHdllTYPE PEFLSHdll;
extern fp_PHFL1dllTYPE PHFL1dll;
extern fp_PHFLSHdllTYPE PHFLSHdll;
extern fp_PQFLSHdllTYPE PQFLSHdll;
extern fp_PREOSdllTYPE PREOSdll;
extern fp_PRESSdllTYPE PRESSdll;
extern fp_PSFL1dllTYPE PSFL1dll;
extern fp_PSFLSHdllTYPE PSFLSHdll;
extern fp_PUREFLDdllTYPE PUREFLDdll;
extern fp_QMASSdllTYPE QMASSdll;
extern fp_QMOLEdllTYPE QMOLEdll;
extern fp_SATDdllTYPE SATDdll;
extern fp_SATEdllTYPE SATEdll;
extern fp_SATHdllTYPE SATHdll;
extern fp_SATPdllTYPE SATPdll;
extern fp_SATSdllTYPE SATSdll;
extern fp_SATTdllTYPE SATTdll;
extern fp_SETAGAdllTYPE SETAGAdll;
extern fp_SETKTVdllTYPE SETKTVdll;
extern fp_SETMIXdllTYPE SETMIXdll;
extern fp_SETMODdllTYPE SETMODdll;
extern fp_SETREFdllTYPE SETREFdll;
extern fp_SETUPdllTYPE SETUPdll;
extern fp_SPECGRdllTYPE SPECGRdll;
extern fp_SUBLPdllTYPE SUBLPdll;
extern fp_SUBLTdllTYPE SUBLTdll;
extern fp_SURFTdllTYPE SURFTdll;
extern fp_SURTENdllTYPE SURTENdll;
extern fp_TDFLSHdllTYPE TDFLSHdll;
extern fp_TEFLSHdllTYPE TEFLSHdll;
extern fp_THERM0dllTYPE THERM0dll;
extern fp_THERM2dllTYPE THERM2dll;
extern fp_THERM3dllTYPE THERM3dll;
extern fp_THERMdllTYPE THERMdll;
extern fp_THFLSHdllTYPE THFLSHdll;
extern fp_TPFLSHdllTYPE TPFLSHdll;
extern fp_TPRHOdllTYPE TPRHOdll;
extern fp_TQFLSHdllTYPE TQFLSHdll;
extern fp_TRNPRPdllTYPE TRNPRPdll;
extern fp_TSFLSHdllTYPE TSFLSHdll;
extern fp_VIRBdllTYPE VIRBdll;
extern fp_VIRCdllTYPE VIRCdll;
extern fp_WMOLdllTYPE WMOLdll;
extern fp_XMASSdllTYPE XMASSdll;
extern fp_XMOLEdllTYPE XMOLEdll;
extern fp_HEATdllTYPE HEATdll;

